-- Supabase_Sstup.sql
-- Pokemon Card Generator: schema, policies, and inspection queries
-- Generated: 2026-03-12
--
-- This script is intentionally idempotent where possible so you can run it
-- multiple times while evolving your project.

begin;

-- ============================================================================
-- 0) Extensions
-- ============================================================================
create extension if not exists pgcrypto;

-- ============================================================================
-- 1) Core Tables
-- ============================================================================

-- TABLE: public.trainers
-- Purpose:
--   One row per authenticated user. Stores trainer-facing identity data used in UI.
-- Used by app for:
--   - trainer_name on profile page and navbar
-- Relationships:
--   - id references auth.users(id)
create table if not exists public.trainers (
  id uuid primary key references auth.users(id) on delete cascade,
  trainer_name text not null default 'Trainer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- TABLE: public.trainer_profiles
-- Purpose:
--   Extended profile settings and public profile controls.
-- Used by app for:
--   - avatar_url
--   - bio
--   - name_public
-- Recent changes reflected here:
--   - avatar_url support for navbar/profile avatar rendering
--   - bio and name_public controls in profile settings
create table if not exists public.trainer_profiles (
  trainer_id uuid primary key references public.trainers(id) on delete cascade,
  avatar_url text,
  bio text,
  name_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- TABLE: public.trainer_preferences
-- Purpose:
--   Per-user UI and gameplay preferences.
-- Used by app for:
--   - favorite_type
--   - show_animations
-- Recent changes reflected here:
--   - persisted animation preference used in UI toggles
create table if not exists public.trainer_preferences (
  trainer_id uuid primary key references public.trainers(id) on delete cascade,
  favorite_type text,
  show_animations boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trainer_preferences_favorite_type_chk check (
    favorite_type is null or favorite_type in (
      'bug','dark','dragon','electric','fairy','fighting','fire','flying',
      'ghost','grass','ground','ice','normal','poison','psychic','rock',
      'steel','water'
    )
  )
);

-- TABLE: public.captured_pokemon
-- Purpose:
--   User collection of saved Pokemon cards and their serialized card snapshot.
-- Used by app for:
--   - collection/recent/profile counts
--   - favorites
--   - preventing duplicate captures
create table if not exists public.captured_pokemon (
  id bigint generated by default as identity primary key,
  trainer_id uuid not null references public.trainers(id) on delete cascade,
  pokemon_id integer not null,
  pokemon_name text not null,
  card_data jsonb not null default '{}'::jsonb,
  rarity text not null default 'common',
  is_favorite boolean not null default false,
  date_captured timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint captured_pokemon_rarity_chk check (
    rarity in ('common','uncommon','rare','epic','mythical','legendary','ultra','mythic')
  )
);

-- Unique per-trainer capture to match app duplicate-check behavior
create unique index if not exists uq_captured_pokemon_trainer_pokemon
  on public.captured_pokemon(trainer_id, pokemon_id);

create index if not exists idx_captured_pokemon_trainer_date
  on public.captured_pokemon(trainer_id, date_captured desc);

create index if not exists idx_captured_pokemon_trainer_favorite
  on public.captured_pokemon(trainer_id, is_favorite);

-- TABLE: public.trainer_teams
-- Purpose:
--   Saved teams for builder/battle features.
-- Used by app for:
--   - create/update/delete teams
--   - battle team selection
create table if not exists public.trainer_teams (
  id bigint generated by default as identity primary key,
  trainer_id uuid not null references public.trainers(id) on delete cascade,
  team_name text not null,
  team_description text,
  pokemon_ids integer[] not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trainer_teams_size_chk check (coalesce(array_length(pokemon_ids, 1), 0) = 6)
);

create index if not exists idx_trainer_teams_trainer_created
  on public.trainer_teams(trainer_id, created_at desc);

-- ============================================================================
-- 2) Recent Schema Upgrades (safe ALTERs)
-- ============================================================================
-- These align existing databases with recent app capabilities.

alter table if exists public.trainer_profiles
  add column if not exists avatar_url text;

alter table if exists public.trainer_profiles
  add column if not exists bio text;

alter table if exists public.trainer_profiles
  add column if not exists name_public boolean not null default false;

alter table if exists public.trainer_preferences
  add column if not exists favorite_type text;

alter table if exists public.trainer_preferences
  add column if not exists show_animations boolean not null default true;

-- ============================================================================
-- 3) Trigger Helpers
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Recreate triggers safely

drop trigger if exists trg_trainers_set_updated_at on public.trainers;
create trigger trg_trainers_set_updated_at
before update on public.trainers
for each row execute function public.set_updated_at();

drop trigger if exists trg_trainer_profiles_set_updated_at on public.trainer_profiles;
create trigger trg_trainer_profiles_set_updated_at
before update on public.trainer_profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_trainer_preferences_set_updated_at on public.trainer_preferences;
create trigger trg_trainer_preferences_set_updated_at
before update on public.trainer_preferences
for each row execute function public.set_updated_at();

drop trigger if exists trg_captured_pokemon_set_updated_at on public.captured_pokemon;
create trigger trg_captured_pokemon_set_updated_at
before update on public.captured_pokemon
for each row execute function public.set_updated_at();

drop trigger if exists trg_trainer_teams_set_updated_at on public.trainer_teams;
create trigger trg_trainer_teams_set_updated_at
before update on public.trainer_teams
for each row execute function public.set_updated_at();

-- Optional: auto-create trainer/profile/preferences rows after auth signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.trainers (id, trainer_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'trainer_name', split_part(new.email, '@', 1), 'Trainer')
  )
  on conflict (id) do nothing;

  insert into public.trainer_profiles (trainer_id)
  values (new.id)
  on conflict (trainer_id) do nothing;

  insert into public.trainer_preferences (trainer_id)
  values (new.id)
  on conflict (trainer_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ============================================================================
-- 4) Row Level Security (RLS)
-- ============================================================================

alter table public.trainers enable row level security;
alter table public.trainer_profiles enable row level security;
alter table public.trainer_preferences enable row level security;
alter table public.captured_pokemon enable row level security;
alter table public.trainer_teams enable row level security;

-- trainers policies
create policy if not exists trainers_select_own
on public.trainers
for select
using (auth.uid() = id);

create policy if not exists trainers_update_own
on public.trainers
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy if not exists trainers_insert_own
on public.trainers
for insert
with check (auth.uid() = id);

-- trainer_profiles policies
create policy if not exists trainer_profiles_select_own
on public.trainer_profiles
for select
using (auth.uid() = trainer_id);

create policy if not exists trainer_profiles_insert_own
on public.trainer_profiles
for insert
with check (auth.uid() = trainer_id);

create policy if not exists trainer_profiles_update_own
on public.trainer_profiles
for update
using (auth.uid() = trainer_id)
with check (auth.uid() = trainer_id);

-- trainer_preferences policies
create policy if not exists trainer_preferences_select_own
on public.trainer_preferences
for select
using (auth.uid() = trainer_id);

create policy if not exists trainer_preferences_insert_own
on public.trainer_preferences
for insert
with check (auth.uid() = trainer_id);

create policy if not exists trainer_preferences_update_own
on public.trainer_preferences
for update
using (auth.uid() = trainer_id)
with check (auth.uid() = trainer_id);

-- captured_pokemon policies
create policy if not exists captured_pokemon_select_own
on public.captured_pokemon
for select
using (auth.uid() = trainer_id);

create policy if not exists captured_pokemon_insert_own
on public.captured_pokemon
for insert
with check (auth.uid() = trainer_id);

create policy if not exists captured_pokemon_update_own
on public.captured_pokemon
for update
using (auth.uid() = trainer_id)
with check (auth.uid() = trainer_id);

create policy if not exists captured_pokemon_delete_own
on public.captured_pokemon
for delete
using (auth.uid() = trainer_id);

-- trainer_teams policies
create policy if not exists trainer_teams_select_own
on public.trainer_teams
for select
using (auth.uid() = trainer_id);

create policy if not exists trainer_teams_insert_own
on public.trainer_teams
for insert
with check (auth.uid() = trainer_id);

create policy if not exists trainer_teams_update_own
on public.trainer_teams
for update
using (auth.uid() = trainer_id)
with check (auth.uid() = trainer_id);

create policy if not exists trainer_teams_delete_own
on public.trainer_teams
for delete
using (auth.uid() = trainer_id);

-- ============================================================================
-- 5) Storage Bucket + Policies (Avatar Upload)
-- ============================================================================
-- Bucket used by app: trainers-avatars

insert into storage.buckets (id, name, public)
values ('trainers-avatars', 'trainers-avatars', false)
on conflict (id) do nothing;

-- Users can upload/read/delete only inside their own folder path: <uid>/...
-- NOTE: auth.uid()::text must match first folder segment in object key.

create policy if not exists avatar_storage_select_own
on storage.objects
for select
using (
  bucket_id = 'trainers-avatars'
  and split_part(name, '/', 1) = auth.uid()::text
);

create policy if not exists avatar_storage_insert_own
on storage.objects
for insert
with check (
  bucket_id = 'trainers-avatars'
  and split_part(name, '/', 1) = auth.uid()::text
);

create policy if not exists avatar_storage_update_own
on storage.objects
for update
using (
  bucket_id = 'trainers-avatars'
  and split_part(name, '/', 1) = auth.uid()::text
)
with check (
  bucket_id = 'trainers-avatars'
  and split_part(name, '/', 1) = auth.uid()::text
);

create policy if not exists avatar_storage_delete_own
on storage.objects
for delete
using (
  bucket_id = 'trainers-avatars'
  and split_part(name, '/', 1) = auth.uid()::text
);

-- ============================================================================
-- 6) Useful Verification / Inspection Queries
-- ============================================================================

-- A) List all relevant tables in public schema
-- select table_name
-- from information_schema.tables
-- where table_schema = 'public'
--   and table_name in ('trainers','trainer_profiles','trainer_preferences','captured_pokemon','trainer_teams')
-- order by table_name;

-- B) Column-level schema details
-- select table_name, column_name, data_type, is_nullable, column_default
-- from information_schema.columns
-- where table_schema = 'public'
--   and table_name in ('trainers','trainer_profiles','trainer_preferences','captured_pokemon','trainer_teams')
-- order by table_name, ordinal_position;

-- C) List RLS policies
-- select schemaname, tablename, policyname, cmd, permissive, roles, qual, with_check
-- from pg_policies
-- where schemaname in ('public','storage')
--   and (
--     tablename in ('trainers','trainer_profiles','trainer_preferences','captured_pokemon','trainer_teams')
--     or tablename = 'objects'
--   )
-- order by schemaname, tablename, policyname;

-- D) Check if RLS is enabled
-- select n.nspname as schema_name, c.relname as table_name, c.relrowsecurity as rls_enabled
-- from pg_class c
-- join pg_namespace n on n.oid = c.relnamespace
-- where n.nspname = 'public'
--   and c.relname in ('trainers','trainer_profiles','trainer_preferences','captured_pokemon','trainer_teams')
-- order by c.relname;

-- E) Duplicate capture sanity check (should return zero rows)
-- select trainer_id, pokemon_id, count(*) as duplicate_count
-- from public.captured_pokemon
-- group by trainer_id, pokemon_id
-- having count(*) > 1;

-- F) Team size sanity check (should return zero rows)
-- select id, trainer_id, team_name, array_length(pokemon_ids, 1) as team_size
-- from public.trainer_teams
-- where coalesce(array_length(pokemon_ids, 1), 0) <> 6;

-- G) Profile completeness per trainer
-- select
--   t.id,
--   t.trainer_name,
--   (tp.trainer_id is not null) as has_profile,
--   (pref.trainer_id is not null) as has_preferences,
--   tp.avatar_url,
--   pref.show_animations
-- from public.trainers t
-- left join public.trainer_profiles tp on tp.trainer_id = t.id
-- left join public.trainer_preferences pref on pref.trainer_id = t.id
-- order by t.created_at desc;

commit;
